export var Config = (function () {
    // -------------------------------------
    // REQUIRED
    // Available at https://dev.facetec.com/account
    // NOTE: This field is auto-populated by the FaceTec SDK Configuration Wizard.
    var DeviceKeyIdentifier = "dLztRsP4qgcWrQJUrkQQcsIqJygmeGEN";

    // -------------------------------------
    // REQUIRED
    // The URL to call to process FaceTec SDK Sessions.
    // In Production, you likely will handle network requests elsewhere and without the use of this variable.
    // See https://dev.facetec.com/security-best-practices?link=facetec-server-rest-endpoint-security for more information.
    // NOTE: This field is auto-populated by the FaceTec SDK Configuration Wizard.
    var BaseURL = "https://api.facetec.com/api/v3.1/biometrics";

    // -------------------------------------
    // REQUIRED
    // The FaceScan Encryption Key you define for your application.
    // Please see https://dev.facetec.com/facemap-encryption-keys for more information.
    // NOTE: This field is auto-populated by the FaceTec SDK Configuration Wizard.
    var PublicFaceScanEncryptionKey =
        "-----BEGIN PUBLIC KEY-----\n" +
        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5PxZ3DLj+zP6T6HFgzzk\n" +
        "M77LdzP3fojBoLasw7EfzvLMnJNUlyRb5m8e5QyyJxI+wRjsALHvFgLzGwxM8ehz\n" +
        "DqqBZed+f4w33GgQXFZOS4AOvyPbALgCYoLehigLAbbCNTkeY5RDcmmSI/sbp+s6\n" +
        "mAiAKKvCdIqe17bltZ/rfEoL3gPKEfLXeN549LTj3XBp0hvG4loQ6eC1E1tRzSkf\n" +
        "GJD4GIVvR+j12gXAaftj3ahfYxioBH7F7HQxzmWkwDyn3bqU54eaiB7f0ftsPpWM\n" +
        "ceUaqkL2DZUvgN0efEJjnWy5y1/Gkq5GGWCROI9XG/SwXJ30BbVUehTbVcD70+ZF\n" +
        "8QIDAQAB\n" +
        "-----END PUBLIC KEY-----"    
        ;

    
    // -------------------------------------
    // Convenience method to initialize the FaceTec SDK.
    // NOTE: This function is auto-populated by the FaceTec SDK Configuration Wizard based on your UI Customizations you picked in the Configuration Wizard GUI.
    
    function initializeFromAutogeneratedConfig(FaceTecSDK, callback) {
        FaceTecSDK.initializeInDevelopmentMode(this.DeviceKeyIdentifier, this.PublicFaceScanEncryptionKey,
            function (initializedSuccessfully) {
                callback(initializedSuccessfully);
            });
    };
    
    
    // This app can modify the customization to demonstrate different look/feel preferences
    // NOTE: This function is auto-populated by the FaceTec SDK Configuration Wizard based on your UI Customizations you picked in the Configuration Wizard GUI.
    function retrieveConfigurationWizardCustomization(FaceTecSDK) {
        var sdkImageDirectory = "../../core-sdk/FaceTec_images/";
        
        // Set a default customization
        var defaultCustomization = new FaceTecSDK.FaceTecCustomization();

                return defaultCustomization;
    };

    // NOT WHITE TEXT COLOR START
    function retrieveLowLightConfigurationWizardCustomization(FaceTecSDK) {
        var defaultCustomization = retrieveConfigurationWizardCustomization(FaceTecSDK);
        this.currentLowLightCustomization = defaultCustomization;
        return defaultCustomization;
    }
    // NOT WHITE TEXT COLOR END
    // WHITE TEXT COLOR START
    // -------------------------------------
    // NOTE: Changing text color for Low Light mode so it's readable
    function retrieveLowLightConfigurationWizardCustomization(FaceTecSDK) {
        // CUSTOMIZATION PROPERTIES START
        // For Color Customization
        var textColor = "#000000";

        // Set a default customization
        var lowLightCustomization = retrieveConfigurationWizardCustomization(FaceTecSDK);

        // Set Guidance Customization
        lowLightCustomization.guidanceCustomization.foregroundColor = textColor;

        // Set Result Screen Customization
        lowLightCustomization.resultScreenCustomization.foregroundColor = textColor;

        // Set ID Scan Customization
        lowLightCustomization.idScanCustomization.selectionScreenForegroundColor = textColor;


        // CUSTOMIZATION PROPERTIES ASSIGNMENT END
        return lowLightCustomization;
    }
    // WHITE TEXT COLOR END
    // NOT BLACK TEXT COLOR START
    function retrieveDynamicDimmingConfigurationWizardCustomization(FaceTecSDK) {
        var defaultCustomization = retrieveConfigurationWizardCustomization(FaceTecSDK);
        this.currentDynamicDimmingCustomization = defaultCustomization;
        return defaultCustomization;
    }
    // NOT BLACK TEXT COLOR END
    // BLACK TEXT COLOR START
    // -------------------------------------
    // NOTE: Changing text color for Dynamic Dimming mode so it's readable
    function retrieveDynamicDimmingConfigurationWizardCustomization(FaceTecSDK) {
        // CUSTOMIZATION PROPERTIES START
        // For Color Customization
        var textColor = "#ffffff";

        // Set a default customization
        var dynamicDimmingCustomization = retrieveConfigurationWizardCustomization(FaceTecSDK);

        // Set Guidance Customization
        dynamicDimmingCustomization.guidanceCustomization.foregroundColor = textColor;

        // Set Result Screen Customization
        dynamicDimmingCustomization.resultScreenCustomization.foregroundColor = textColor;

        // Set ID Scan Customization
        dynamicDimmingCustomization.idScanCustomization.selectionScreenForegroundColor = textColor;


        // CUSTOMIZATION PROPERTIES ASSIGNMENT END
        return dynamicDimmingCustomization;
    }
    // BLACK TEXT COLOR END

    var currentCustomization;
    var currentLowLightCustomization;
    var currentDynamicDimmingCustomization;

    // -------------------------------------
    // Boolean to indicate the FaceTec SDK Configuration Wizard was used to generate this file.
    // In this Sample App, if this variable is true, a "Config Wizard Theme" will be added to this App's "Toggle Colors & Themes" menu,
    // and choosing this option will set the FaceTec SDK UI/UX Customizations to the Customizations that you selected in the
    // Configuration Wizard.
    var wasSDKConfiguredWithConfigWizard = true;

    
    return {
        wasSDKConfiguredWithConfigWizard,
        DeviceKeyIdentifier,
        BaseURL,
        PublicFaceScanEncryptionKey,
        initializeFromAutogeneratedConfig,
        currentCustomization,
        currentLowLightCustomization,
        currentDynamicDimmingCustomization,
        retrieveConfigurationWizardCustomization,
        retrieveLowLightConfigurationWizardCustomization,
        retrieveDynamicDimmingConfigurationWizardCustomization
    };
    

    
})();
